### PR TITLE
Fixed syntax and other small typos

### PR DESCRIPTION
**Pull request by mklb**

### CODE REVIEW

**Comment by H3xept** [comment]
I cannot accept the whole pull request, there are some errors in it. I'll correct some lines tho, thanks for the interest.

**Comment by H3xept** [comment]
More specifically your solution was not correct here

**If installed via CocoaPods**

```
-#import "Stomt.h"       
+#import <StomtiOS/Stomt.h>
```

**If installed manually**

```
-#import <StomtiOS/Stomt.h>      
+#import "Stomt.h"
```

The CocoaPods version needs to be imported referring to`"Stomt.h"` or eventually to 
`<Stomt-iOS-SDK/Stomt.h>`
This is due to my naming convention problem at the beginning of the development.
So in order to keep it clean, i just wanted to stay with "Stomt.h". 

Talking about the second correction, you are using an external framework so you need to search "Stomt.h" in "global scope" so you should use <> brackets.

**Comment by mklb** [comment]
I have no idea how you use cocoa pods but when you want to import a pod: it will be always `<PodName/Podnahme.h>` try it yourself ;D In this case its: #import `<Stomt-iOS-SDK/Stomt.h>` you´re right. I din´t correct it, I just swapped them

**Comment by H3xept** [comment]
As i said,`#import <Stomt-iOS-SDK/Stomt.h>`is the most common way, but since the SDK is named StomtiOS, it could be confusing. I'll fix this problem in one of the upcoming versions of the SDK, thanks for your pull requests:)

**Pull request closed without merging**
